# Generated by Django 5.2.5 on 2025-08-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
        insert into store_collection (name, description, created_at, updated_at) values
        ('Default Collection', 'This is the default collection', NOW(), NOW()
        );
        """, """
        delete from store_collection where name='Default Collection';
        """),
    ]
